// COMMONS — data access layer.
//
// The seed JSON is the source of truth and the demo-safe read path: it is loaded
// once at startup and served directly, so reads never depend on Firestore being
// up (and never burn the Firestore daily quota). When Firestore credentials are
// present (on the deployed service), live citizen submissions are written there
// and merged on read — but the seed always backs the response. For Phase 1 the
// read path is pure seed JSON; the Firestore merge seam is marked below.
import { readFileSync } from "node:fs";
import path from "node:path";
import type {
  AgentRun,
  CivicPulse,
  ExposureGridCell,
  FootprintDoc,
  Issue,
  Report,
  Reporter,
  Snapshot,
  StatusEvent,
  TwinDoc,
} from "../shared/types.ts";
import { logger } from "./lib/logger.ts";
import {
  addLiveIssue,
  hydrate,
  listLiveIssues,
  setSeedLifecycle,
  withTracking,
} from "./state/store.ts";

// Seed JSON lives at <repo>/seed and is committed, so it ships with the build.
// Resolve from process.cwd() (the container working dir) so this works whether
// the server runs via tsx (dev) or as the esbuild CJS bundle (production).
const SEED = path.resolve(process.cwd(), "seed");
const WARD = "blr-174-hsr";

function load<T>(file: string, fallback: T): T {
  try {
    return JSON.parse(readFileSync(path.join(SEED, file), "utf8")) as T;
  } catch (err) {
    logger.warn({ err, file }, "seed_load_failed");
    return fallback;
  }
}

// Loaded once at startup (the container is long-lived between requests).
const reports = load<Report[]>("reports.json", []);
const reporters = load<Reporter[]>("reporters.json", []);
const issues = load<Issue[]>("issues.json", []);
const exposureGrid = load<ExposureGridCell[]>("exposureGrid.json", []);
// The frozen agent-pipeline trace (Phase 2). Null until `npm run agents` has run;
// the read path serves it as-is (the demo trace, 0 RPD).
const agentRun = load<AgentRun | null>("agentRun.json", null);
// Time Machine snapshots (Phase 3) — month-end frames of the quadrant state.
const snapshots = load<Snapshot[]>("snapshots.json", []);
// Digital-Twin building footprints (disclosed-synthetic, density/height from the
// real exposure grid). Optional — the twin renders fine without them.
const footprintDoc = load<FootprintDoc | null>("footprints.json", null);

logger.info(
  { reports: reports.length, issues: issues.length, cells: exposureGrid.length },
  "seed_loaded",
);

// ── Civic Pulse (derived from the issue set; the real narrative is generated by
// the Civic Pulse agent in a later phase, but the structured fields are derived
// here so the spine renders a complete, honest summary). ─────────────────────────
function buildCivicPulse(): CivicPulse {
  const ranked = [...issues].sort((a, b) => b.impactScore - a.impactScore);
  const top = ranked[0];
  const loudest = [...issues].sort((a, b) => b.attentionScore - a.attentionScore)[0];
  const blindSpot = issues.find((i) => i.reversal?.overruledAttention);
  return {
    status: "Stable, with one emerging risk",
    emergingRisk: top ? top.title : "—",
    mostIgnoredProblem: blindSpot ? blindSpot.title : (top?.title ?? "—"),
    attentionPattern: loudest ? `Over-focused on “${loudest.title}”` : "—",
    civicBlindSpot: blindSpot
      ? `Citizens rank “${loudest?.title}” loudest, but the AI-assessed top risk is “${blindSpot.title}”.`
      : "—",
    resolutionBottleneck: "Jurisdiction ownership across BWSSB / BBMP-SWD",
    priorityRecommendation: top ? `Inspect: ${top.title}` : "—",
    narrative:
      "HSR Layout is broadly stable, but the loudest complaint is not the most dangerous problem. " +
      "Several quiet, high-impact issues — a choked stormwater drain, a load-bearing wall crack, an " +
      "unlit pedestrian stretch — sit below the community's attention while a much-discussed pothole " +
      "draws the noise. COMMONS surfaces the gap.",
  };
}

// ── Digital Twin (derived; full modelling lands in Phase 3). ─────────────────────
function buildTwin(): TwinDoc {
  const openImpact = issues.reduce((s, i) => s + i.impactScore, 0) / Math.max(issues.length, 1);
  return {
    wardId: WARD,
    name: "HSR Layout (BBMP Ward 174)",
    infraHealth: Math.round(100 - openImpact),
    issueVelocity: Math.round((reports.length / 18) * 10) / 10, // reports/month avg
    issueDensity: Math.round((issues.length / Math.max(exposureGrid.length, 1)) * 100) / 100,
    engagementIndex:
      Math.round(
        (reports.reduce((s, r) => s + r.engagement.upvotes + 2 * r.engagement.replies, 0) /
          Math.max(reports.length, 1)) *
          10,
      ) / 10,
    resolutionEffectiveness: 0, // no issues resolved yet in the seed timeline
    emergingRisks: [...issues]
      .sort((a, b) => b.impactScore - a.impactScore)
      .slice(0, 3)
      .map((i) => i.title),
    exposureGrid,
    lastSnapshotId: "",
  };
}

const civicPulse = buildCivicPulse();
const twin = buildTwin();

// ── Demo lifecycle seeding ────────────────────────────────────────────────────────
// The six demo issues are given realistic, honest lifecycle states derived from
// their OWN attributes (recurrence, impact rank, SLA). The STATES are designed
// (disclosed-synthetic, like the rest of the corpus), but the SLA-overdue math and
// the recurred-as-systemic logic run live against the wall clock. The thesis is
// visible in the states themselves: the loudest, lowest-impact issue (the pothole)
// is RESOLVED, while the quiet, high-impact ones sit ASSIGNED-and-overdue.
function ev(
  status: StatusEvent["status"],
  at: string,
  note: string,
  actor: StatusEvent["actor"],
): StatusEvent {
  return { status, at, note, actor };
}

// The lifecycle dates are anchored to NOW (resolved once at server boot) so the
// live SLA clock always reads believably — "9 days overdue", never "150 days" —
// no matter what day the demo runs. This is a runtime value (data.ts loads when
// the server starts, never in the offline seed-freeze scripts), so reading the
// clock here is correct; it does not affect the frozen seed corpus. Dates are
// derived as "N days before boot", so the overdue windows hold their shape.
const LIFECYCLE_ANCHOR = Date.now();
function daysBeforeAnchor(n: number): string {
  return new Date(LIFECYCLE_ANCHOR - n * 86_400_000).toISOString();
}

function seedDemoLifecycle(): void {
  // ISS_NOISE — the loud pothole the crowd obsessed over. Got fixed fast BECAUSE it
  // was loud. The control case: attention got it resolved while danger waited.
  setSeedLifecycle(
    "ISS_NOISE",
    "resolved",
    [
      ev("reported", daysBeforeAnchor(18), "Filed — pothole on the main road", "citizen"),
      ev(
        "acknowledged",
        daysBeforeAnchor(17),
        "High community attention flagged it fast",
        "authority",
      ),
      ev("assigned", daysBeforeAnchor(16), "Routed to BBMP Road Infrastructure", "authority"),
      ev("resolved", daysBeforeAnchor(10), "Patched and closed within the 10-day SLA", "authority"),
    ],
    daysBeforeAnchor(16),
    0,
    0.78,
  );

  // ISS_REC — the recurrence. Resolved before, came back (3rd time, per its memory).
  // The accountability flagship: tracking turns "closed 3×" into "systemic".
  setSeedLifecycle(
    "ISS_REC",
    "recurred",
    [
      ev("reported", daysBeforeAnchor(40), "First report — drain backing up", "citizen"),
      ev("assigned", daysBeforeAnchor(38), "Routed to BBMP SWD", "authority"),
      ev("resolved", daysBeforeAnchor(28), "Desilted and closed", "authority"),
      ev(
        "recurred",
        daysBeforeAnchor(7),
        "Same failure, 3rd time in 162 days — the symptom was closed, not the cause",
        "system",
      ),
    ],
    daysBeforeAnchor(38),
    0,
    0.51,
  );

  // ISS_HC1 — impact 81, the top hidden crisis. Assigned 24 days ago against a 15-day
  // SLA → ~9 days overdue. The model ranked it #1; the clock proves it's neglected.
  setSeedLifecycle(
    "ISS_HC1",
    "assigned",
    [
      ev("reported", daysBeforeAnchor(30), "Filed — choked stormwater drain", "citizen"),
      ev("acknowledged", daysBeforeAnchor(26), "Seen by ward office", "authority"),
      ev("assigned", daysBeforeAnchor(24), "Routed to BBMP SWD Division, SLA 15 days", "authority"),
    ],
    daysBeforeAnchor(24),
    0,
    0.17,
  );

  // ISS_HC2 — impact 80, a load-bearing wall crack with a 3-DAY SLA. Assigned 19 days
  // ago → ~16 days overdue. The most dangerous + tightest SLA, still open.
  setSeedLifecycle(
    "ISS_HC2",
    "assigned",
    [
      ev("reported", daysBeforeAnchor(25), "Filed — crack in a load-bearing wall", "citizen"),
      ev("acknowledged", daysBeforeAnchor(22), "Seen — structural risk noted", "authority"),
      ev("assigned", daysBeforeAnchor(19), "Routed to BBMP, structural SLA 3 days", "authority"),
    ],
    daysBeforeAnchor(19),
    0,
    0.15,
  );

  // ISS_HC3 — impact 62, unlit pedestrian stretch. Acknowledged, not yet assigned —
  // sitting in the gap the model flagged.
  setSeedLifecycle(
    "ISS_HC3",
    "acknowledged",
    [
      ev("reported", daysBeforeAnchor(28), "Filed — unlit pedestrian stretch", "citizen"),
      ev("acknowledged", daysBeforeAnchor(24), "Logged by BESCOM", "authority"),
    ],
    null,
    0,
    0.23,
  );

  // ISS_SYN — the synthesis issue. The latent cause was just surfaced by the model;
  // acknowledged, awaiting routing across BWSSB/BBMP jurisdictions.
  setSeedLifecycle(
    "ISS_SYN",
    "acknowledged",
    [
      ev("reported", daysBeforeAnchor(12), "Surfaced by cross-report synthesis", "system"),
      ev("acknowledged", daysBeforeAnchor(10), "Flagged for multi-department review", "authority"),
    ],
    null,
    0,
    0.3,
  );

  logger.info({ seeded: 6 }, "demo_lifecycle_seeded");
}

// Lay down the deterministic demo baseline first, THEN replay any persisted
// real-world deltas (live submissions + visitor corroborations/advances) on top.
seedDemoLifecycle();
hydrate();

// ── Public read API (seed path; Firestore merge seam noted inline) ───────────────
export const data = {
  ward: WARD,
  // The seed issues PLUS any live-submitted ones, each merged with its runtime
  // lifecycle/corroboration overlay (live attentionScore + recomputed quadrant +
  // tracking block). The raw seed array is never mutated.
  listIssues(): Issue[] {
    return [...issues, ...listLiveIssues()].map(withTracking);
  },
  // The raw seed issue with NO overlay — used internally where the frozen score is
  // wanted (e.g. ranking against the baseline before applying live signal).
  rawIssue(id: string): Issue | undefined {
    return issues.find((i) => i.issueId === id) ?? listLiveIssues().find((i) => i.issueId === id);
  },
  getIssue(id: string): Issue | undefined {
    const raw = this.rawIssue(id);
    return raw ? withTracking(raw) : undefined;
  },
  // Register a live-submitted issue so it appears in the matrix and is trackable.
  addLiveIssue(issue: Issue): void {
    addLiveIssue(issue);
  },
  listReports(): Report[] {
    return reports;
  },
  getReporter(id: string): Reporter | undefined {
    return reporters.find((r) => r.id === id);
  },
  getNeighborhood(): { twin: TwinDoc; civicPulse: CivicPulse } {
    return { twin, civicPulse };
  },
  getAgentRun(): AgentRun | null {
    return agentRun;
  },
  listSnapshots(): Snapshot[] {
    return snapshots;
  },
  getFootprints(): FootprintDoc | null {
    return footprintDoc;
  },
};
