// COMMONS — data access layer.
//
// The seed JSON is the source of truth and the demo-safe read path: it is loaded
// once at startup and served directly, so reads never depend on Firestore being
// up (and never burn the Firestore daily quota). When Firestore credentials are
// present (on the deployed service), live citizen submissions are written there
// and merged on read — but the seed always backs the response. For Phase 1 the
// read path is pure seed JSON; the Firestore merge seam is marked below.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import type {
  Issue, Report, Reporter, TwinDoc, ExposureGridCell, CivicPulse,
} from "../shared/types.ts";
import { logger } from "./lib/logger.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SEED = path.resolve(__dirname, "../seed");
const WARD = "blr-174-hsr";

function load<T>(file: string, fallback: T): T {
  try {
    return JSON.parse(readFileSync(path.join(SEED, file), "utf8")) as T;
  } catch (err) {
    logger.warn({ err, file }, "seed_load_failed");
    return fallback;
  }
}

// Loaded once at startup (the container is long-lived between requests).
const reports = load<Report[]>("reports.json", []);
const reporters = load<Reporter[]>("reporters.json", []);
const issues = load<Issue[]>("issues.json", []);
const exposureGrid = load<ExposureGridCell[]>("exposureGrid.json", []);

logger.info(
  { reports: reports.length, issues: issues.length, cells: exposureGrid.length },
  "seed_loaded",
);

// ── Civic Pulse (derived from the issue set; the real narrative is generated by
// the Civic Pulse agent in a later phase, but the structured fields are derived
// here so the spine renders a complete, honest summary). ─────────────────────────
function buildCivicPulse(): CivicPulse {
  const ranked = [...issues].sort((a, b) => b.impactScore - a.impactScore);
  const top = ranked[0];
  const loudest = [...issues].sort((a, b) => b.attentionScore - a.attentionScore)[0];
  const blindSpot = issues.find((i) => i.reversal?.overruledAttention);
  return {
    status: "Stable, with one emerging risk",
    emergingRisk: top ? top.title : "—",
    mostIgnoredProblem: blindSpot ? blindSpot.title : top?.title ?? "—",
    attentionPattern: loudest ? `Over-focused on “${loudest.title}”` : "—",
    civicBlindSpot: blindSpot
      ? `Citizens rank “${loudest?.title}” loudest, but the AI-assessed top risk is “${blindSpot.title}”.`
      : "—",
    resolutionBottleneck: "Jurisdiction ownership across BWSSB / BBMP-SWD",
    priorityRecommendation: top ? `Inspect: ${top.title}` : "—",
    narrative:
      "HSR Layout is broadly stable, but the loudest complaint is not the most dangerous problem. " +
      "Several quiet, high-impact issues — a choked stormwater drain, a load-bearing wall crack, an " +
      "unlit pedestrian stretch — sit below the community's attention while a much-discussed pothole " +
      "draws the noise. COMMONS surfaces the gap.",
  };
}

// ── Digital Twin (derived; full modelling lands in Phase 3). ─────────────────────
function buildTwin(): TwinDoc {
  const openImpact = issues.reduce((s, i) => s + i.impactScore, 0) / Math.max(issues.length, 1);
  return {
    wardId: WARD,
    name: "HSR Layout (BBMP Ward 174)",
    infraHealth: Math.round(100 - openImpact),
    issueVelocity: Math.round((reports.length / 18) * 10) / 10, // reports/month avg
    issueDensity: Math.round((issues.length / Math.max(exposureGrid.length, 1)) * 100) / 100,
    engagementIndex:
      Math.round(
        (reports.reduce((s, r) => s + r.engagement.upvotes + 2 * r.engagement.replies, 0) /
          Math.max(reports.length, 1)) * 10,
      ) / 10,
    resolutionEffectiveness: 0, // no issues resolved yet in the seed timeline
    emergingRisks: [...issues]
      .sort((a, b) => b.impactScore - a.impactScore)
      .slice(0, 3)
      .map((i) => i.title),
    exposureGrid,
    lastSnapshotId: "",
  };
}

const civicPulse = buildCivicPulse();
const twin = buildTwin();

// ── Public read API (seed path; Firestore merge seam noted inline) ───────────────
export const data = {
  ward: WARD,
  listIssues(): Issue[] {
    // SEAM: when Firestore is configured, merge live-submitted issues here.
    return issues;
  },
  getIssue(id: string): Issue | undefined {
    return issues.find((i) => i.issueId === id);
  },
  listReports(): Report[] {
    return reports;
  },
  getReporter(id: string): Reporter | undefined {
    return reporters.find((r) => r.id === id);
  },
  getNeighborhood(): { twin: TwinDoc; civicPulse: CivicPulse } {
    return { twin, civicPulse };
  },
};
